version: 43.0.9
pageUuid: db52a384-cac4-11eb-a183-0f4b6a737944
appTemplate:
  tests:
    array: []
  urlFragmentDefinitions: []
  appStyles: ''
  appThemeId: null
  preloadedAppJavaScript: null
  pageLoadValueOverrides: []
  customDocumentTitle: ''
  isGlobalWidget: false
  isFetching: false
  testEntities:
    array: []
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  preloadedAppJSLinks:
    array: []
  version: 2.70.13
  responsiveLayoutDisabled: false
  createdAt: null
  customShortcuts:
    array: []
  loadingIndicatorsDisabled: false
