version: 43.0.9
pageUuid: 02905932-c98f-11eb-ae3d-7b11ddee9d19
appTemplate:
  tests:
    array: []
  urlFragmentDefinitions: []
  appStyles: ''
  appThemeId: null
  preloadedAppJavaScript: null
  pageLoadValueOverrides: []
  customDocumentTitle: ''
  isGlobalWidget: false
  isFetching: false
  testEntities:
    array: []
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  preloadedAppJSLinks:
    array: []
  version: 2.70.11
  responsiveLayoutDisabled: false
  createdAt: null
  customShortcuts:
    array: []
  loadingIndicatorsDisabled: false
